name: Docker Image CI
env:
  AWS_REGION : us-east-2
  AWS_ECR_URL: 084175654614.dkr.ecr.us-east-2.amazonaws.com/test-repo
  
on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
#     - name: Clone Github repo
#       uses: actions/checkout@v2
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET }}
#         aws-region: ${{ env.AWS_REGION }}
        
#     - name: Login to Amazon ECR
#       uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{ env.AWS_ECR_URL }}:${{ github.sha }}
      
#     - name: Docker push image
#       run: docker push ${{ env.AWS_ECR_URL }}:${{ github.sha }}
     - name: Kubectl
       run: kubectl --help
     - name: Helm
       run: helm --help
